### ISSUE TITLE
Podman stats with no containers listed should throw an error

### ISSUE THREAD

**Issue by mheon** [projectatomic/libpod#1028]
Right now, we allow `podman stats` to run with no containers listed (Reproducer: `podman stats` with no arguments or container IDs/names). This displays a refreshing, empty screen. We should return an error instead, as doing stats on no containers is pointless.

**Comment by rhatdan** [comment]
@haircommander PTAL

**Comment by baude** [comment]
I disagree with this.  When no containers are present, stats should run with an empty screen.  This is the docker behaviour and it is consistent with other monitoring tools.

**Comment by TomSweeneyRedHat** [comment]
Assuming @baude 's empty screen means showing just a header line, then +1 for me.

**Comment by mheon** [comment]
@baude Appears to be correct per docker, though the screen should have the header line. Right now, we do not, but Docker does.

**Comment by rhatdan** [comment]
No docker behaviour is wrong, lets just exit out when this happens, with a message saying no containers.
Otherwise it is tough to figure out whether the tool failed or their are no containers.

**Comment by baude** [comment]
The header should be there... but if this tool is used for monitoring, it would be nice to have it run without a container so you could capture startup, etc.  Sort of like how you can run vmstat 1 and then apply workload.  Otherwise, decide as you will; if you change behavior, make sure you then test and change all behaviours related to it running and having containers stop.
