### ISSUE TITLE
podman run --entrypoint= should remove entrypoint completely

### ISSUE THREAD

**Issue by redbaron** [projectatomic/libpod#572]
/kind bug

**Description**

`podman run --entrypoint= <image>` doesn't remove entrypoint as it does on docker

**Describe the results you received:**
```
container create failed: container_linux.go:348: starting container process caused "exec: \"\": executable file not found in $PATH"
```

**Additional information you deem important (e.g. issue happens only occasionally):**

docker behaves as expected, effect is as if ENTRYPOINT was not specified in the Dockerfile at all

**Output of `podman version`:**

```
podman version
Version:       0.3.4
Go Version:    go1.9.4
OS/Arch:       linux/amd64
```

**Comment by mheon** [comment]
It looks like our command-building logic is faulty for empty string entrypoints - we're still injecting the element into the command, instead of clearing entrypoint.

Looking at the code, I see that entrypoint is a StringSliceFlag, which leads me to wonder why? I don't think you'll ever want to set entrypoint twice... That sould probably be looked at.

**Comment by mheon** [comment]
@baude Mind taking a look? I believe you wrote the current entrypoint handling
