### ISSUE TITLE
RFC: porting libpod to containers/image/pkg/sysregistriesv2

### ISSUE THREAD

**Issue by vrothberg** [projectatomic/libpod#721]
## Why moving to sysregistriesv2?

The new package [1] allows to configure more aspects related to distribution than the old v1 API, including mirrors, specifying a URL with an http{,s} scheme, setting them to be insecure and also to allow searching in case an unqualified image is specified (e.g., "alpine:latest" instead of "docker.io/library/alpine:latest"). Moreover, we can use the Prefix semantics to translate namespaces and repositories or to just match certain namespaces on a given repository.

## What's the problem moving to sysregistriesv2?

So far, the biggest obstacle is that we cannot separate the registry URI (http/https) and if it's a secure one or not, which has been a core requirement when discussing the design [2]. One way to approach this is extending the `types.ImageReference` interface with something like `RegistryURL()` but there are more ways to approach that. We also need to extend the `docker_client` code, which seems to only use http if `DockerInsecureSkipTLSVerify` is set and use https by default, and make the code use the URI scheme specified in the registries URL.

Hence the questions:

- How shall we proceed? What's a potential way of addressing that?

- Shall we introduce the concept of URI schemes or stick with how it's done at the moment? (This weould mean that we remove the URI handling from sysregistriesv2, and that insecure implies using http and skipping verification.)

- Additional issues I may have missed?

[1] https://github.com/containers/image/pull/429
[2] https://github.com/containers/image/issues/397#issuecomment-359125521

**Comment by rhatdan** [comment]
I like what you are doing @vrothberg I think this will make configuring registries a lot more straight forward.

**Comment by mheon** [comment]
Regarding registry protocol specified in the URI: I'm of slightly mixed feelings here... We currently maintain a list of registries we allow insecure operations against, so I don't think we should respect the registry's requested scheme if it wants HTTP and it's not listed as an insecure registry (we should produce a good error describing why we won't pull from it, though).

**Comment by mheon** [comment]
@mtrmac PTAL, this looks like it will require some changes in the containers/image interface

**Comment by mtrmac** [comment]
> So far, the biggest obstacle is that we cannot separate the registry URI (http/https) and if it's a secure one or not, which has been a core requirement when discussing the design [2].

Am I overlooking something? The `sysregistriesv2` package, as merged in https://github.com/containers/image/pull/429, does have an independent “insecure” flag both for registries and mirrors. So we have already separated the two.

> One way to approach this is extending the types.ImageReference interface with something like RegistryURL() but there are more ways to approach that. We also need to extend the docker_client code, which seems to only use http if DockerInsecureSkipTLSVerify is set and use https by default, and make the code use the URI scheme specified in the registries URL.

As the libpod code stands right now, it is not necessary to cram the security flag into the “image name” as parsed by `alltransports.ParseImageName` / `ImageTransport.ParseReference`; it is passed separately in `types.SystemContext.DockerInsecureSkipTLSVerify`, and AFAICT that approach works just as well with `sysregistriesv2`; https://github.com/projectatomic/libpod/blob/b44d4fb1ec05aec958a63bdfa3d344cdf4b4da8f/libpod/image/pull.go#L182 could be directly adapted to `sysregistriesv2` with no changes to c/image.

AFAICS, in principle, nothing prevents c/image users from interpreting the `Prefix`→`URL` mapping, or using the list of mirrors, either (although the code would be a bit non-trivial and should not need to be repeated all over the place, see below).

Or maybe I am missing the problem that needs to be solved.

---

While integration of `sysregistriesv2` as a direct replacement of `sysregistries` in all users seems to be fairly straightforward, I think we should seriously consider consolidating most of that code in to c/image itself, so that it acts on the config file without every caller having to do it itself.  The caller should ideally be just able to do ~ `alltransports.ParseImageName(userSpecifiedString).NewImageSource()` and get a client that Just Works.

(Well, maybe not the search, because I _hate_ it, notably it pretty much breaks reasoning about user intent when verifying signatures, and the way it changes handling of existing `docker://busybox` references would be an invisible API break.)

The `Insecure` flag, the `Prefix`→`URL` mapping look like things that can and should be handled transparently in c/image without the callers having to care. The `Mirrors` list seems likely to be better handled in c/image as well, although there is a stronger case that the caller may want to have control over that process, maybe distributing the use of mirrors when pulling many images at once, so that they all don’t hammer the first one in the list, or something like that. But the default is likely to work for most callers, so we can start with c/image handling mirrors, and we can always add an opt-out via `types.SystemContext`.

**Comment by mtrmac** [comment]
> As the libpod code stands right now, it is not necessary to cram the security flag into the “image name” as parsed by `alltransports.ParseImageName` / `ImageTransport.ParseReference`

(BTW as much as having a string format is useful and necessary for a CLI, it’s also a _pain_ to design and maintain because it is either unusably complex for humans to use (e.g. strictly semantically correct JSON), or it uses meta-characters which complicate or prevent handling of unusual strings, or it heuristically tries to guess what the user meant depending on context, and is unpredicatable/unreliable.  E.g. we’ve ended up with several transports unable to handle paths which contain colons because they use a colon as a separator.

A better UX is for the “image name” not to embed various options, and for those options to be instead available in separate, individually documented and validated, CLI options.  The downside to that is that every single caller needs to implement, document and validate the options, so there certainly is a balance to be struck. At least for the “insecure” flag, we mostly already have the options in place.)

**Comment by mtrmac** [comment]
> > So far, the biggest obstacle is that we cannot separate the registry URI (http/https) and if it's a secure one or not, which has been a core requirement when discussing the design [2].
>
> Am I overlooking something? The sysregistriesv2 package, as merged in containers/image#429, does have an independent “insecure” flag both for registries and mirrors. So we have already separated the two.

… Ah, right. The difficulty is not with the “insecure” flag, it’s that the c/image behavior, as described above, makes the protocol specified in the config file ignored and pointless.

As far as the [linked comment](https://github.com/containers/image/issues/397#issuecomment-359125521) goes, I was only worried about a config that forces the user to say `http` to mean means “HTTPS but without certificate verification”, and we no longer have that problem.  As discussed above, I would be fine with not having the protocol in the config at all, I guess (with absolutely no supporting data, to be fair) that the distinction is rarely likely to matter in practice.

If you think this does matter:

1) One way would be for `c/image/docker` to parse and interpret the config file itself. Then the question of how to express HTTP/HTTPS in the API mostly goes away.

2) It would be consistent with the other cases, although not all that pretty, to express this as an option in `types.SystemContext`, maybe an yes/no/autodetect enum `DockerUseTLS`.

I’d prefer either dropping the schema from the config, or option 1.

**Comment by vrothberg** [comment]
> While integration of sysregistriesv2 as a direct replacement of sysregistries in all users seems to be fairly straightforward, I think we should seriously consider consolidating most of that code in to c/image itself, so that it acts on the config file without every caller having to do it itself. 

I agree. I really want to get rid of libpod's `registries` package as having a wrapper for an API usually means that the API isn't complete. Things such as `registries.GetInsecureRegistries()` could safely be moved into c/image.

> The Insecure flag, the Prefix→URL mapping look like things that can and should be handled transparently in c/image without the callers having to care.

I wouldn't put that into c/image, as I want to have full control over the c/image library. In case we move all the sysregv2 semantics into c/image pulling, for instance, having full control over what's going to happen would mean that we had to extend the API with yet more boolean switches (e.g., disable_mirrors, disable_prefixing, etc.). If we keep the logic at the user site, c/image can just pull an image without further reasoning and the user can decide if the mirrors or prefix semantics shall be used or not.

> … Ah, right. The difficulty is not with the “insecure” flag, it’s that the c/image behavior, as described above, makes the protocol specified in the config file ignored and pointless.

Luckily there is no user of sysregv2 yet :-) I am quite happy to know we don't have to go down the rabbit hole. I must have misread your comment when working on the sysregv2 API as I thought you wanted to have https with TLS verification skip as well.

> I’d prefer either dropping the schema from the config, or option 1.

I completely agree. As mentioned above, we could add an extra API to get the insecure registries as well.

@mtrmac I propose to follow your suggestion and remove the URI schemes from sysregsv2 (and unconditionally throw a warning if one is specified) and to also extend the API to get insecure registries. We can then remove the redundant libpod `registries` package. After that, supporting sysregv2 is pretty straight forward. Did I miss anything?

Once I get an ACK from your side, I will start preparing a PR to polish sysregv2.

**Comment by vrothberg** [comment]
@mtrmac I was playing a bit with the idea of forbidding any URI schemes in sysregsv2, and it turns out that the URL validation gets pretty screwed. Without an URI scheme, net/url's parsing isn't able to distinguish between `user:password` and the URI scheme yielding very imprecise error messages.

This made me reflect more on the issue, so I want to propose another alternative to the two you proposed above:

3. Use `http` and `https` URI scheme to distinguish insecure and secure registries. I know there are (valid) concerns, but Docker is already using this semantics. The issue discussed above can then be solved by setting the skip verify flag when `http` is used.

A more or less related topic, but something that makes me prefer option 3: For the SUSE CaaS Platform and openSUSE's Kubic project, we are already using registry mirrors (configurable via the Velum dashboard using a backport of the current upstream PR). Once things are merged into Docker and CRI-O, it would be nice to be as close as possible (semantically) without having to special-case too many details.

Sorry for changing my mind, but I _believe_ it's more usable that way.

**Comment by mtrmac** [comment]
> > The Insecure flag, the Prefix→URL mapping look like things that can and should be handled transparently in c/image without the callers having to care.
>
> I wouldn't put that into c/image, as I want to have full control over the c/image library. In case we move all the sysregv2 semantics into c/image pulling, for instance, having full control over what's going to happen would mean that we had to extend the API with yet more boolean switches (e.g., disable_mirrors, disable_prefixing, etc.). If we keep the logic at the user site, c/image can just pull an image without further reasoning and the user can decide if the mirrors or prefix semantics shall be used or not.

The point of a system-wide config file is that the behavior is system-wide :) Individual applications should typically not be deciding to interpret only parts of it, at least not in the common case and without a good reason.

Applications which do have a good reason can already exercise full control, by pointing `types.SystemContext.SystemRegistriesConfPath` at a custom file (including `/dev/null`). (This allows the application to do everything, but small localized edits like “respect the users’ config, but use insecure mode for a single host name” would be very difficult. Does that matter? What do you need?)

**Comment by mtrmac** [comment]
>  I was playing a bit with the idea of forbidding any URI schemes in sysregsv2, and it turns out that the URL validation gets pretty screwed. Without an URI scheme, net/url's parsing isn't able to distinguish between `user:password` and the URI scheme yielding very imprecise error messages.

Ouch.

> Use `http` and `https` URI scheme to distinguish insecure and secure registries. I know there are (valid) concerns, but Docker is already using this semantics.

Pre-existing practice would certainly be a strong argument. Where is this being used?

---

Another possible alternative: Instead of parsing the values as `url.URL`, use the regexes in `c/image/docker/reference`.  That’s what the data _actually is_; `docker.io/library/busybox` is actually the URL `https://registry-1.docker.io/v2/library/busybox/manifests/latest` + all the referenced blob files.  The namespace/repo parts of the docker/distribution protocol do not accept arbitrary characters allowed in URLs; `?query=string#anchor` is not allowed either.

The flip side is that, assuming we want the `URL` and `Prefix` fields to always be hostname[/namespaces…], c/image/docker/reference does not provide an API to do that right now; there’s `ParseNormalizedNamed` which can accept such input but interprets differently for hostname-only values (`example.com` == `docker.io/library/example.com`.  It’s seems plausible enough to make `DomainRegexp` public and make the parsing possible to do externally, or to add another parser to the package.  (Using regexps like that my not give very friendly error messages either, though.)

This seems to be conceptually correct but a not-quite-trivial amount of code.

---

Or we could go with a two-line hack, `uri, err := url.Parse("https://" + input);` …; `uri.Scheme = ""`.  Not _correct_ by any means but the if `url.Parse` does report an error, it will be appropriately matched to the relevant component of the input, and the simplicity is a bit appealing.

**Comment by vrothberg** [comment]
>> Use http and https URI scheme to distinguish insecure and secure registries. I know there are (valid) concerns, but Docker is already using this semantics.

> Pre-existing practice would certainly be a strong argument. Where is this being used?

It's part of the design of https://github.com/moby/moby/pull/34319#issuecomment-381766390 for a long while (see quote below). It's not yet merged, but those semantics are carved into stone.

- "_Registry URLs must have a scheme (http:// or https://); this largely makes --insecure-registry obsolete, but if desirable, we can add an TLSnoVerify option in future, to account for (e.g.) MITM proxies etc._"

You might notice that we're about to celebrate the Moby PR's birthday soon, so we'll certainly be quicker with c/images and libpod. While working on sysgregsv2 I tried to be close to the Moby PR, but I wasn't aware that the insecure switch controls that for image pulling.

In case we decide to remove URI schemes from sysregsv2, I would prefer to use the `https` fallback to allow a sane parsing, just as you suggested:

>Or we could go with a two-line hack, uri, err := url.Parse("https://" + input); …; uri.Scheme = "". Not correct by any means but the if url.Parse does report an error, it will be appropriately matched to the relevant component of the input, and the simplicity is a bit appealing.

However, then I would change `{Registry,Mirror}.URL` to be a string and do the parsing only to validate and to sanitize the input.

**Comment by vrothberg** [comment]
@mtrmac Sorry to be pushy, but I am eager to get mirror support into Podman. What's your take on my last comment?

**Comment by mtrmac** [comment]
> It's part of the design of moby/moby#34319 (comment) for a long while (see quote below). It's not yet merged, but those semantics are carved into stone.
> 
> "Registry URLs must have a scheme (http:// or https://); this largely makes --insecure-registry obsolete, but if desirable, we can add an TLSnoVerify option in future, to account for (e.g.) MITM proxies etc."

It’s a bit hard to take an unmerged PR as semantics “carved into stone” :)

And anyway, this design has AFAICS “`http:` means no TLS”, not “`http:` allows both no TLS and unauthenticated TLS”.  It means dropping support for the `TLSnoVerify` case entirely (until some “future”).

---

More or less every TLS client ends up having an option to ignore certificate failures.  I don’t have a _really good_ argument that such an option _should_ exist; probably in the majority of cases where I’ve seen the option used it shouldn’t have been. Still, I do see `skopeo --tls-verify=false` often enough in various shell transcripts, for whatever reasons.

The existence of such an option _may_ be just a cargo-culted practice of making such a concession to convenience, something that may not actually be _necessary_.  I’d be happy to hear that none of these are actually needed, I don’t know how to tell whether that’s the case. (And there’s also the question whether c/image wants to be a trailblazer for the hard-line “TLS means TLS” approach.) @rhatdan , others, WDYT?

---

WRT specific use cases: MITM proxies should be handled by actually installing their certificate as a CA root, to be at all practical. I’m more worried about disaster recovery, “special situations”, and the like:

- Legitimate disagreements between the maintainer of the server and of the client about the needed security for the connection.
  - A notable special case for docker/distribution registries: with digest references, and possibly signatures, the integrity of the TLS connection to the registry may not matter for clients who rely on the digests—but the registry still needs to support TLS for integrity of images delivered to clients who don’t know the digests.
  - Also, forensic investigations, where a former production server is examined on a separate unquestioned network, and the goal is only to see the contents of the server and not to protect against the network attacking, ideally without changing the server configuration in any way.
- Temporary workarounds (“I have a new laptop and I urgently need to check an image without spending hours to install a full corporate build”. This one is typically iffy.)
- Recovering from CA certificate mismanagement (rolled over the root of trust without deploying it to consumers, which would need to be updated from the rolled over registry), both for manual changes and possibly when the CA is automatically managed by a product like OpenShift (I do hope we would not fail this badly, but Kubernetes does seem to be moving towards shipping core parts of the infrastructure as containers).
- Crazy corporate box-ticking/department politics (“we must use TLS but we don’t have to care”, “the other department set up the box and we can’t wait for them to fix their certificates”).  (Years ago, in a completely unrelated project, I have encountered a customer who insisted on using TLS but not doing any verification. The customer ultimately got the option they asked for added.)

OTOH, there _is_ a genuine big risk that temporary workarounds stay enabled forever; and even if they are very temporary, an attacker may need to only successfully compromise an image transport once.

---

Overall, with the little information I have, I don’t currently really feel comfortable with not having the ability to use TLS in an insecure manner at all. It’s a risk to use such an option, but it seems to be a risk users want to take fairly frequently.

And with the strings not being URLs semantically at all, using schemes is not really adding clarity.

So, I’d prefer a format with docker-like references (whether parsed through `c/image/docker/reference` or `url.Parse("http://"+…)` and letting some invalid strings through), and a separate “insecure” boolean.

**BUT** I do know I have a pretty bad track record on UX design (`volume_key`!?); I’d love other opinions.

---

> However, then I would change `{Registry,Mirror}.URL` to be a string and do the parsing only to validate and to sanitize the input.

Yes, that makes perfect sense. (The fields may not even need to be called URL, pedantically, but that doesn’t matter that much.)

**Comment by rhatdan** [comment]
I agree, we need to have a get out of jail free card.  Where user just tells the tool to make it happen.  --tls-verify=false.  These things get broken too often and easily.

**Comment by vrothberg** [comment]
@mtrmac @rhatdan Thanks a lot for checking. It looks like we are going for removing the URI schemes and keeping the insecure switch. I will prepare an update to c/image then. I am pretty busy right now, but I will try to work on that asap.

**Comment by vrothberg** [comment]
I see this issue as resolved. We can discuss the details in the upcoming PR in c/image.
